In [1]:
pip install schedule

Requirement already satisfied: schedule in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (1.2.2)

Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install lxml

Requirement already satisfied: lxml in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (5.3.0)

Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install html5lib

Requirement already satisfied: html5lib in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (1.1)
Requirement already satisfied: six>=1.9 in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in /opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages (from html5lib) (0.5.1)

Note: you may need to restart the kernel to use updated packages.

In [4]:
import requests
import pandas as pd
import datetime
import pytz
import schedule
import time
from datetime import datetime
from io import StringIO
import os

In [5]:
url = "https://www.zse.co.zw/price-sheet/"

In [6]:
def get_todays_data():
  response = requests.get(url)
  data = pd.read_html(StringIO(response.text))
  df = pd.DataFrame(data[0])
  df.columns = df.iloc[0]
  df = df[1:]
  df = df.dropna()
  return df

def get_open_price():
  df = get_todays_data()
  open_price = df[['Company Name','Opening Price']].T
  open_price.columns  = open_price.iloc[0]
  open_price = open_price[1:]
  open_price.index.name = 'Date'
  open_price = open_price.rename(index={open_price.index[0]: datetime.now(pytz.timezone('Africa/Harare'))})
  return open_price

def get_close_price():
  df = get_todays_data()
  close_price = df[['Company Name','Closing Price']].T
  close_price.columns  = close_price.iloc[0]
  close_price = close_price[1:]
  close_price.index.name = 'Date'
  close_price = close_price.rename(index={close_price.index[0]: datetime.now(pytz.timezone('Africa/Harare'))})
  return close_price

def get_vol_traded():
  df = get_todays_data()
  vol_traded = df[['Company Name','Total Traded Volume']].T
  vol_traded.columns  = vol_traded.iloc[0]
  vol_traded = vol_traded[1:]
  vol_traded.index.name = 'Date'
  vol_traded = vol_traded.rename(index={vol_traded.index[0]: datetime.now(pytz.timezone('Africa/Harare'))})
  return vol_traded

In [7]:
#open_price = get_open_price()
#close_price = get_close_price()
#vol_traded = get_vol_traded()

In [8]:
def save_data(open_price: pd.DataFrame, close_price: pd.DataFrame, vol_traded: pd.DataFrame):
    # Extract the index name (timestamp) from the DataFrames
    #timestamp = open_price.index[0]
    
    # Create the directory path using the timestamp
    #directory_path = f'archive/{timestamp}'
    
    # Create the directory if it doesn't exist
    #os.makedirs(directory_path, exist_ok=True)
    
    # Save the DataFrames to JSON files with the timestamped directory
    open_price.to_json('archive-single-file/open_price.json', orient='split', date_format='iso')
    close_price.to_json('archive-single-file/close_price.json', orient='split', date_format='iso')
    vol_traded.to_json('archive-single-file/vol_traded.json', orient='split', date_format='iso')

# Example usage

In [9]:
open_json = pd.read_json('archive-single-file/open_price.json', orient = 'split')
close_json = pd.read_json('archive-single-file/close_price.json', orient = 'split')
vol_json = pd.read_json('archive-single-file/vol_traded.json', orient = 'split')

In [10]:
#this is the code that needs to run everyday
def update_data():
  open_price = pd.concat([open_json, get_open_price()], axis=0) # Update the variables
  close_price = pd.concat([close_json, get_close_price()], axis=0)
  vol_traded = pd.concat([vol_json, get_vol_traded()], axis=0)

  return open_price, close_price, vol_traded
#update_data()[0].to_json('/Users/apple/Desktop/open_price1.json', orient='split', date_format='iso')
save_data(update_data()[0], update_data()[1] , update_data()[2])

In [11]:
#open_json1 = pd.read_json('/Users/apple/Desktop/open_price1.json', orient = 'split')
#open_json = pd.read_json('/Users/apple/Desktop/open_price.json', orient = 'split')
open_json

,Afdis Distillers Limited,Amalgamated Regional Trading (Art) Holdings Limited,Ariston Holdings Limited,British American Tobacco Zimbabwe Limited,Cafca Limited,Cbz Holdings Limited,Cfi Holdings Limited,Dairibord Holdings Limited,Delta Corporation Limited,Ecocash Holdings Zimbabwe Limited,...,Turnall Holdings Limited,Unifreight Africa Limited,Willdale Limited,Zb Financial Holdings Limited,Zeco Holdings Limited,Zimbabwe Newspapers (1980) Limited,Zimre Holdings Limited,Bridgefort Capital Limited,Bridgefort Capital Limited Class B,Meikles Limited
2024-11-10,808.0,62.00,7.8200,11995.0,1560.000,1499.0000,372.25,196.2500,1942.6048,40.0500,...,6.50,249.95,5.4380,750.0000,0.0018,6,55.2500,1.5,2.64,429.95
2024-11-11,808.0,62.00,7.8200,11995.0,1560.000,1499.0000,372.25,196.2500,1942.6048,40.0500,...,6.50,249.95,5.4380,750.0000,0.0018,6,55.2500,1.5,2.64,429.95
2024-11-12,808.0,62.00,7.8000,11900.0,1560.000,1398.6137,428.05,196.2500,1942.9869,38.5197,...,6.50,249.95,5.3735,750.0000,0.0018,6,55.2445,1.5,2.64,429.95
2024-11-13,808.0,62.00,7.7486,10115.0,1560.000,1399.5131,428.05,196.0000,1912.9224,39.9615,...,6.50,250.00,5.3735,730.0000,0.0018,6,55.2500,1.5,2.64,441.98
2024-11-14,808.0,62.00,7.7683,8800.0,1560.000,1399.5131,492.25,196.0833,1913.1514,38.1814,...,6.12,250.00,5.2000,730.0000,0.0018,6,55.2500,1.5,2.64,420.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-01-28,700.0,24.15,6.0000,9900.0,2039.645,840.0000,418.00,195.5000,1350.4617,29.0000,...,5.50,212.00,5.9500,480.0000,0.0018,15,17.0000,NaN,NaN,NaN
2025-01-29,700.0,27.05,6.0000,9900.0,2040.000,840.0000,480.00,195.5000,1341.9328,29.0000,...,5.50,212.00,5.9500,480.0000,0.0018,15,17.0000,NaN,NaN,NaN
2025-01-30,700.0,27.05,6.0000,9900.0,1800.000,840.0000,480.00,195.5000,1334.7743,29.0000,...,5.50,212.00,5.5000,412.7273,0.0018,15,17.0000,NaN,NaN,NaN
2025-01-31,700.0,27.05,6.0000,9900.0,1800.000,840.0000,480.00,195.5000,1314.8209,29.0000,...,5.50,212.00,5.5000,470.0000,0.0018,15,17.0000,NaN,NaN,NaN
2025-02-03,700.0,27.05,6.0000,9900.0,1800.000,840.0000,480.00,195.5000,1296.9277,29.7500,...,5.50,212.00,5.5000,470.0000,0.0018,15,19.5500,NaN,NaN,NaN

In [12]:
# import pandas as pd

# Load JSON data into a DataFrame
# def load_json_data(file_path: str) -> pd.DataFrame:
#     return pd.read_json(file_path, orient='split')

# # Example usage
# open_price_df = load_json_data('open_price.json')
# close_price_df = load_json_data('close_price.json')
# vol_traded_df = load_json_data('vol_traded.json')

# # Display the DataFrames
# open_price_df.head()
# close_price_df.head()
# vol_traded_df.head()

In [13]:
#schedule.every(1).day.do(update_data)

#while True:
   #schedule.run_pending()
   #time.sleep(1)

   #print('jobs:', len(schedule.get_jobs()))